language: node_js
node_js:
  - 'node'
env:
  - EXTENSION_ID=hlepfoohegkhhmjieoechaddaejaokhf
deploy:
  - # Publishes tagged version. Expects tag to be valid version
    provider: script
    skip_cleanup: true
    script: npm run release
    on:
      tags: true
      condition: $TRAVIS_TAG != hotfix

  - # Creates versioned git tag when tag is `hotfix`
    provider: script
    skip_cleanup: true
    script: npm run create-git-tag
    on:
      tags: true
      condition: $TRAVIS_TAG = hotfix

  - # Creates versioned git tag on daily Travis cronjobs if it has recent commits
    provider: script
    skip_cleanup: true
    script: npm run create-git-tag
    on:
      branch: master
      condition: $(npm run can-release --silent)
